CMake fixes.
Adds a definition for Visual Studio 2017 >=15.8 but <16 to handle
error C2338, by specifying that the compiler should correctly do
extended alignment.

Sending YAML_CPP_BUILD_TESTS:BOOL=OFF to the external yaml build
prevents the build from failing due to a combination of yaml 6.3
bundling gtest-1.8.0 (which has tr1 warnings), and
the external yaml build set to treat warnings as errors.

CMP0074 NEW specifies that <PACKAGE>_ROOT environment variables are used
in find_package, e.g. Boost_ROOT.