Fix linking with pthread on Arch Linux
Fix an issue on Arch Linux where there was an undefined reference to
pthread. Need to explicitly include the pthread library. This fix uses
CMakes FindThreads (find_package(Threads)) to look for pthread. On
windows this should have no effect, but on linux it should add a
-lpthread to the build flags.